version: '3.1'

services:
  db: 
    image: mysql:5.5.62
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=ajmc
    volumes:
      - ./da:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    image: php:7.1.12-apache
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pos
      - DB_USERNAME=root
      - DB_PASSWORD=ajmc
    volumes:
      # - './pos:/var/www/html'
      - './POS_MIRAMAR:/var/www/html'
    ports:
      - 8000:80
    links:  
      - db 
 

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8080:80
    # environment:
    #   - PMA_ARBITRARY=1